on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'qmuntal/draco tag to clone'     
        required: true
name: CDraco
jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
            generator: Unix Makefiles
            libname: libcdraco_linux_amd64
          - os: macos-latest
            cc: clang
            cxx: clang++
            generator: Unix Makefiles
            libname: libcdraco_darwin_amd64
          - os: windows-latest
            cc: x86_64-w64-mingw32-gcc
            cxx: x86_64-w64-mingw32-g++
            generator: MinGW Makefiles
            libname: libcdraco_windows_amd64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: git clone --depth 1 --branch ${{ github.event.inputs.tag }} https://github.com/qmuntal/draco.git ../draco
      - run: mkdir _gh_build
        working-directory: ../draco
      - run: |
          cmake -G "${{ matrix.generator }}" \
            -DDRACO_C_API=ON \
            -DDRACO_POINT_CLOUD_COMPRESSION=ON \
            -DDRACO_MESH_COMPRESSION=ON \
            -DDRACO_STANDARD_EDGEBREAKER=ON \
            -DCMAKE_BUILD_TYPE=Release ..
        working-directory: ../draco/_gh_build
        shell: bash
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
      - run: make -j10
        working-directory: ../draco/_gh_build
      - run: |
          cp ../draco/_gh_build/libcdraco.a ./lib/${{ matrix.libname }}.a
        shell: bash
      - run: git checkout -b update-${{ matrix.libname }}-${{ github.event.inputs.tag }}
      - run: git commit -m "Update ${{ matrix.libname }} with v${{ github.event.inputs.tag }}"
      - run: git push -u origin update-${{ matrix.libname }}-${{ github.event.inputs.tag }}
